In [1]:
import numpy as np

Exercise 1: Create a 1D NumPy array of numbers from 0 to 9

In [2]:
arr=np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


Write a code to convert a 1D array to a 2D array with 2 rows.

In [3]:
arr=np.arange(6)
arr=arr.reshape(2,3)
print(arr)

[[0 1 2]
 [3 4 5]]


Exercise 3: Print Array Attributes
Instructions: Print the following attributes of the array:

The shape of the array.
The number of array dimensions.
The size of each element in bytes.

In [4]:
arr=np.array([[1,2],[3,4],[5,6],[7,8]],dtype=np.uint16)
print(arr)
print("Shape of the array",arr.shape)
print(arr.ndim)
print("Size of each byte:",arr[0,0].itemsize)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Shape of the array (4, 2)
2
Size of each byte: 2


Exercise 4: Create a 3×3 NumPy array of all True


In [5]:
arr=np.array((3,3),dtype=bool)
print(arr)

[ True  True]


Exercise 5: Extract the documentation of NumPy’s arange() function


In [38]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The inter

Exercise 6: Create a 1D array filled with zeros and another filled with ones

In [11]:
print(np.ones(5))

print(np.zeros(4))

[1. 1. 1. 1. 1.]
[0. 0. 0. 0.]


Exercise 7: Create a 1D array of 10 evenly spaced values between 5 and 50


In [12]:
np.linspace(5,50,10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

Exercise 8: Convert a Python list into a NumPy array

In [16]:
li=[1,2,3,4]
arr=np.array(li)
print(arr)
print(arr.dtype)

[1 2 3 4]
int64


Exercise 9: Find the memory size of a NumPy array of numbers from 0 to 9

In [19]:
arr=np.arange(10)
print(arr.nbytes)
print(arr.itemsize*arr.size)


80
80


Exercise 10: Reverse a 1D NumPy array

In [29]:
arr=np.arange(4)
print(arr[::-1])

[3 2 1 0]


Exercise 11: Create a 3×3 identity matrix

In [34]:
marr=np.array([[1,2,3],[4,5,6],[7,8,9]])
marr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
Create a 4×4 array and extract its first row and last column

In [43]:
arr=np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
arr[1,3]

np.int64(7)

In [48]:
arr[:,-1]

array([ 3,  7, 11, 15])

Exercise 13: Extract Odd Rows and Even Columns

In [59]:
sampleArray = np.array([
    [3, 6, 9, 12],
    [15, 18, 21, 24],
    [27, 30, 33, 36],
    [39, 42, 45, 48],
    [51, 54, 57, 60]
])
sampleArray

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [62]:
arr=sampleArray[1::2,::2]
arr

array([[15, 21],
       [39, 45]])

Exercise 14: Stack arrays horizontally


In [68]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

arr=np.hstack((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6])

/Exercise 15: Slice the first two rows and first two columns from a 4×4 array


In [71]:
arr=np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [73]:
arr[:2,:2]

array([[1, 2],
       [5, 6]])

Exercise 16: Replace all odd numbers in a NumPy array with -1

In [80]:
arr=np.arange(10)
print(arr)
arr[arr%2==1]=-1
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Exercise 20: Matrix multiplication


In [82]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c=np.dot(a,b)
print(c)

32


Exercise 21: Compute the mean, median, and standard deviation of a NumPy array


In [83]:
arr = np.array([10, 20, 30, 100, 200, 300])

print("Mean",np.mean(arr))
print("Median:",np.median(arr))
print("SD:",np.std(arr))

Mean 110.0
Median: 65.0
SD: 107.08252269472673


Exercise 22: Remove common items from array

In [92]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

mask=np.setdiff1d(a,b)
print(mask)

[1 2 3 4]


Exercise 23: Normalize a NumPy array (values between 0 and 1)

In [99]:
arr=np.arange(5)
norm=(arr-arr.min())/(arr.max()-arr.min())
print(norm)

[0.   0.25 0.5  0.75 1.  ]


Exercise 24: Get the positions where elements of array a and b match


In [103]:

a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 4, 3, 7, 8])
index=np.where(a==b)
print(index)

(array([0, 2]),)


Exercise 25: Extract numbers from an array
Write a code to extract all numbers from an array that are between 5 and 10 (inclusive).



In [107]:
arr=np.arange(15)
result=arr[(arr>4)&(arr<11)]
print(result)

[ 5  6  7  8  9 10]


Exercise 26: Create a random 3×2 matrix and find its maximum and minimum values


In [115]:
arr=np.random.rand(3,2)
print(arr)
print(arr.max())
print(arr.min())

[[0.83301779 0.19821995]
 [0.66397929 0.62891536]
 [0.33039903 0.27427963]]
0.8330177868602414
0.19821994674312304


Exercise 27: Sorting a NumPy array based on a specific column

In [120]:
sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])

sa=sampleArray[:,1].argsort()
arr=sampleArray[sa]
arr

array([[82, 22, 12],
       [34, 43, 73],
       [53, 94, 66]])

Exercise 28: Delete and Insert a Column in a NumPy Array


In [125]:
import numpy as np

sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumnToAdd = np.array([10, 10, 10])
arr=np.delete(sampleArray,1,axis=1)

re=np.insert(arr,1,newColumnToAdd,axis=1)
re


array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

Exercise 29: Swap column 1 and 2 in a 2D array

In [130]:
arr=np.arange(9).reshape(3,3)
print(arr)

arr[:,[1,2]]=arr[:,[2,1]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [131]:
print(np.random.randint(1,101,size=10))

[66 34 60 80 29 60 87 48 77 97]
